#!/usr/bin/env bash
# NGINX
apt-get update
apt-get install nginx -y
new_string="server_name _;\n\trewrite ^\/redirect_me\/ https:\/\/www.youtube.com\/watch?v=ITbv2wm_14I permanent"
cd /etc/nginx/sites-available
sed -i "s/server_name _;/$new_string/" default
service nginx start
