#!/usr/bin/env bash
# NGINX
apt-get update
apt-get -y install nginx
echo "Holberton School" | tee /usr/share/nginx/html/index.html
red="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=ITbv2wm_14I;\n\t}\n"
sed -i "37i\ $red" /var/www/html/custom_404.html
p404="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
echo "Ceci n'est pas une page" | tee /usr/share/nginx/html/index.html
sed -i "37i\ $p404" /etc/nginx/sites-available/default
service nginx restart
